---
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Chart.Name }}-secrets"
data:
    fernetKey: {{ .Values.fernetKey | b64enc | quote }}
    fernet-key: {{ .Values.fernetKey | b64enc | quote }}
    postgresqlPassword: {{ .Values.db.password | b64enc | quote }}
    postgresqlUser: {{ .Values.db.username | b64enc | quote }}
    webserverSecretKey: {{ .Values.webserverSecretKey | b64enc | quote }}
    webserver-secret-key: {{ .Values.webserverSecretKey | b64enc | quote }}
    gitSshKey: {{ .Values.gitSshKey | b64enc | quote }}
    connection: {{ (printf "postgresql://%s:%s@%s:%S/%S" .Values.db.username .Values.db.password .Values.db.host .Values.db.port .Values.db.databaseName) | b64enc | quote }}
type: Opaque
    